### ISSUE TITLE
请问autojs 现在在哪发布么

### ISSUE THREAD

**Issue by GuopingYe** [SuperMonster002/Hello-Sockpuppet#2]
github上只有4.0.5版本

**Comment by SuperMonster003** [comment]
[Auto.js 交流、内测、答疑、接单QQ群](https://www.autojs.org/topic/3104/auto-js-%E4%BA%A4%E6%B5%81-%E5%86%85%E6%B5%8B-%E7%AD%94%E7%96%91-%E6%8E%A5%E5%8D%95qq%E7%BE%A4)
